---
services:

  api:
    image: 'skaben-api:latest'
    restart: unless-stopped
    env_file: '.env'
    volumes:
      - .:/opt/app/
      - static_volume:/static
      - ./server/static:/static/static
      - files_volume:/media
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network_public
      - network_backbone
    command: |
      sh -c "/opt/app/entrypoint.sh"

  worker_internal:
    <<: &worker
      image: 'skaben-api:latest'
      env_file: '.env'
      volumes:
        - ./server:/opt/app/server/
      depends_on:
        rabbitmq:
          condition: service_healthy
      networks:
        - network_backbone
      restart: unless-stopped
      command: python manage.py start_worker internal

  worker_save:
    <<: *worker
    command: python manage.py start_worker state

  worker_send:
    <<: *worker
    command: python manage.py start_worker client

  worker_mqtt:
    <<: *worker
    command: python manage.py start_worker mqtt

  scheduler:
    <<: *worker
    command: python manage.py start_scheduler

  ### INFRASTRUCTURE ###

  rabbitmq:
    build: './docker/rabbitmq'
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping -n rabbit@rabbitmq
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "15672:15672"
      - "15674:15674"
      - "15675:15675"
      - "15692:15692"
      - "5672:5672"
      - "1883:1883"
      - "8883:8883"
    networks:
      - network_public  # admin interface
      - network_backbone

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - network_backbone

  db:
    image: postgres:13.4
    hostname: db
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U skaben # check .env
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./tmp:/home/root/tmp
    networks:
      - network_backbone
    ports:
      - "5432:5432"
    env_file: ".env"

  nginx:
    build: './docker/nginx'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - static_volume:/static
    depends_on:
      api:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - network_public


volumes:
  db_volume: {}
  redis_data: {}
  static_volume: {}
  files_volume: {}


networks:
  network_backbone: {}
  network_public: {}
