# Generated by Django 5.0.3 on 2024-05-12 19:49

import core.helpers
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceKeepalive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=32, validators=[core.validators.mac_validator])),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64, unique=True, verbose_name='Канал MQTT')),
                ('type', models.CharField(choices=[('simple', 'simple'), ('smart', 'smart')], default='simple', max_length=16, verbose_name='Тип устройства')),
                ('active', models.BooleanField(default=True, help_text='Выключение этого параметра останавливает обработку сообщений в этом канале', verbose_name='Активный топик')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'MQTT устройство',
                'verbose_name_plural': 'MQTT устройства',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_timeout', models.IntegerField(default=10, verbose_name='Задержка посыла PING в канал')),
                ('keep_alive', models.IntegerField(default=60, help_text='Интервал через который устройство будет считаться оффлайн', verbose_name='Keep-alive')),
            ],
        ),
        migrations.CreateModel(
            name='ControlReaction',
            fields=[
                ('uuid', models.UUIDField(default=core.helpers.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Должно быть уникальным', max_length=128, unique=True, verbose_name='Название команды')),
                ('payload', models.JSONField(default=dict, help_text='Указывайте просто dict', verbose_name='Полезная нагрузка')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('routing', models.CharField(blank=True, help_text='Не трогайте это если не знаете что это', max_length=128, null=True, verbose_name='Доп. параметры роутинга')),
                ('exchange', models.CharField(choices=[('mqtt', 'mqtt'), ('internal', 'internal')], default='mqtt', help_text='Не трогайте это если не знаете что это', max_length=64, verbose_name='Выбор Exchange')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.devicetopic')),
            ],
            options={
                'verbose_name': 'MQTT: Реакция на команду',
                'verbose_name_plural': 'MQTT: Реакции на команду',
            },
        ),
    ]
