version: '3'

services:
  pgadmin:
    container_name: skaben-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./pg_backups:/tmp/backups:rw
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"


volumes:
    pgadmin: {}

networks:
    default:
        external: true
        name: skaben_skaben_network

