# Generated by Django 5.0.3 on 2024-05-12 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, help_text='Счетчик примет указанное значение, уровень тревоги может быть сброшен', verbose_name='Значение счетчика')),
                ('comment', models.CharField(default='reason: changed by admin', max_length=64, verbose_name='Причина изменений')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего изменения')),
            ],
            options={
                'verbose_name': 'Тревога: счетчик уровня',
                'verbose_name_plural': 'Тревога: счетчик уровня',
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название статуса')),
                ('info', models.CharField(max_length=256, verbose_name='Описание статуса')),
                ('ingame', models.BooleanField(default=True, help_text='Будет ли статус автоматически изменяться системой счетчика тревоги, или переключиться в него можно только специальным событием или вручную. ', verbose_name='Игровой статус')),
                ('threshold', models.IntegerField(default=-1, help_text='Нижнее значение счетчика счетчика тревоги для переключения в статус. Чтобы отключить авто-переключение - выставьте значение ingame = False', verbose_name='Порог срабатывания ')),
                ('current', models.BooleanField(default=False, verbose_name='Сейчас активен')),
                ('order', models.IntegerField(help_text='используется для идентификации и упорядочивания статуса без привязки к id в БД', unique=True, verbose_name='Порядок')),
                ('auto_change', models.CharField(choices=[('increase', 'Увеличивать'), ('decrease', 'Уменьшать')], default=False, help_text='Включить автоматическое повышение или понижение тревоги со временем', verbose_name='Авто-изменение')),
                ('auto_level', models.IntegerField(default=0, help_text='На сколько изменится уровень тревоги при авто-повышении или авто-понижении', verbose_name='Значение авто-изменения')),
                ('auto_timeout', models.IntegerField(default=0, help_text='Частота срабатывания авто-изменения уровня в секундах', verbose_name='Таймаут авто-изменения')),
                ('counter_increase', models.IntegerField(default=0, help_text='На сколько повысится уровень тревоги при ошибке игрока.', verbose_name='Значение увеличения')),
                ('counter_decrease', models.IntegerField(default=0, help_text='На сколько снизится уровень тревоги при удачном действии игрока.', verbose_name='Значение уменьшения')),
            ],
            options={
                'verbose_name': 'Тревога: именной статус',
                'verbose_name_plural': 'Тревога: именные статусы',
            },
        ),
    ]
